export const products = [
  { name: "Sony PS5", category: "Gaming", points: 1500, image: "/assets/gaming.png" },
  { name: "Nintendo Switch", category: "Gaming", points: 1500, image: "/assets/aerolab-logo.png" },
  { name: "Razer BlackWidow Keyboard", category: "Gaming", points: 500, image: "/assets/headPhone.png" },
  { name: "SteelSeries Controller", category: "Gaming", points: 12500, image: "/assets/keyborad.png" },
  { name: "Logitech G502 Mouse", category: "Gaming", points: 12500, image: "/assets/keyborad.png" },
  { name: "Xbox Series X", category: "Gaming", points: 12500, image: "/assets/laptop.png" },
  { name: "Alienware M15 Laptop", category: "Gaming", points: 500, image: "/assets/samsung-mobile.png" },
  { name: "HyperX Cloud II Headset", category: "Gaming", points: 12500, image: "/assets/SonyPS4-x2.png" },
  { name: "SteelSeries Controller", category: "Gaming", points: 12500, image: "/assets/keyborad.png" },
  { name: "Sony WH-1000XM4", category: "Audio", points: 500, image: "/assets/headPhone.png" },
  { name: "Marshall Emberton", category: "Audio", points: 1500, image: "/assets/aerolab-logo.png" },
  { name: "Bose SoundLink", category: "Audio", points: 12500, image: "/assets/samsung-mobile.png" },
  { name: "JBL Flip 5", category: "Audio", points: 12500, image: "/assets/speaker.png" },
  { name: "Google Nest Hub", category: "Smart Home", points: 12500, image: "/assets/camera.png" },
  { name: "Amazon Echo Show", category: "Smart Home", points: 12500, image: "/assets/chromecast-x2.png" },
  { name: "Vizio OLED TV", category: "Smart Home", points: 12500, image: "/assets/NikonD300-camera.png" },
  { name: "August Smart Lock", category: "Smart Home", points: 1200, image: "/assets/aerolab-logo.png" },
  { name: "Ring Video Doorbell", category: "Smart Home", points: 12500, image: "/assets/headPhone.png" },
  { name: "Philips Hue Starter Kit", category: "Smart Home", points: 12500, image: "/assets/drone-camera.png" },
  { name: "Eufy RoboVac", category: "Smart Home", points: 12500, image: "/assets/InstaxMini-x2.png" },
  { name: "TP-Link Smart Plug", category: "Smart Home", points: 100, image: "/assets/laptop.png" },
  { name: "Arlo Pro 3 Camera", category: "Smart Home", points: 12500, image: "/assets/mobile.png" },
  { name: "Vizio OLED TV", category: "Smart Home", points: 12500, image: "/assets/NikonD300-camera.png" },
  { name: "Philips Ambilight TV", category: "Smart Home", points: 1500, image: "/assets/product-shots.png" },
  { name: "Samsung 4K Monitor", category: "Monitors & TV", points: 2500, image: "/assets/camera.png" },
  { name: "Philips Hue Starter Kit", category: "Smart Home", points: 12500, image: "/assets/drone-camera.png" },
  { name: "LG UltraWide Monitor", category: "Monitors & TV", points: 12500, image: "/assets/aerolab-logo.png" },
  { name: "Dell 27” QHD Monitor", category: "Monitors & TV", points: 12500, image: "/assets/headPhone.png" },
  { name: "BenQ Gaming Monitor", category: "Monitors & TV", points: 12500, image: "/assets/InstaxMini-x2.png" },
  { name: "Samsung Frame TV", category: "Monitors & TV", points: 2500, image: "/assets/InstaxMini-x2.png" },
  { name: "Sony Bravia 55”", category: "Monitors & TV", points: 1500, image: "/assets/laptop.png" },
  { name: "Sony Bravia 55”", category: "Monitors & TV", points: 12500, image: "/assets/tablet.png" },

];
